name: Update Adguardhome

on:
  workflow_dispatch:
  schedule:
    - cron: 30 19 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@main

    - name: Set git identity
      run : |
        git config --local user.name "actions"
        git config --local user.email "action@github.com"

    - name: Check up Adguardhome
      run: |
        now_ver="$(cat $GITHUB_WORKSPACE/adguardhome/Makefile | grep "PKG_VERSION:=" | grep -oE "[0-9.]+")"
        latest_ver="$(curl -L -k --retry 2 --connect-timeout 20 -o - https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest 2>/dev/null|grep -E 'tag_name' |grep -E '[0-9.]+' -o 2>/dev/null)"
        echo -e "Adguardhome Local version: ${now_ver}., cloud version: ${latest_ver}." 
        sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=${latest_ver}/g" $GITHUB_WORKSPACE/adguardhome/Makefile

    - name: Push Commits
      run: |
        git add $GITHUB_WORKSPACE/adguardhome/Makefile
        git commit -m "Update Adguardhome ${latest_ver}"
        git push
