name: Update Adguardhome

on:
  workflow_dispatch:
  schedule:
    - cron: 30 21 * * *

env:
  URL: https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@main

    - name: Set git identity
      run : |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Check up Adguardhome
      run: |
        now_ver="$(grep "PKG_VERSION:=" $GITHUB_WORKSPACE/adguardhome/Makefile | grep -oE "[0-9.]+")"
        latest_ver="$(curl -L -o - ${{ env.URL }} 2>/dev/null|grep -E 'tag_name' |grep -oE "[0-9.]+" 2>/dev/null)"
        echo -e "Adguardhome Local version: v${now_ver}, cloud version: v${latest_ver}" 
        sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=${latest_ver}/g" $GITHUB_WORKSPACE/adguardhome/Makefile
        echo "LOCAL_VER=${now_ver}" >> $GITHUB_ENV
        echo "CLOUD_VER=${latest_ver}" >> $GITHUB_ENV

    - name: Push Commits
      if: env.CLOUD_VER != env.LOCAL_VER
      run: |
        git add $GITHUB_WORKSPACE/adguardhome/Makefile
        git commit -m "Adguardhome:bump to v${{ env.CLOUD_VER }}"
        git push

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 2

